export const users = [
    {
        id: 1,
        first_name: "Scarface",
        last_name: "Banbridge",
        code: "STGI00110011",
        password: "0000",
        email: "sbanbridge0@clickbank.net",
        location: "466 chemin staguim, Montreal, CA",
        phone: "+30-835-535-4220",
        typeofuser: "admin",
        university: "UQAM",
    },
    {
        id: 2,
        first_name: "Devi",
        last_name: "Haythorne",
        code: "AGET00110011",
        password: "0000",
        email: "dhaythorne1@miibeian.gov.cn",
        location: "5555 chemin staguim, Montreal, CA",
        phone: "+86-290-892-0772",
        typeofuser: "agent",
        university: "UQAM",
    },
    {
        id: 3,
        first_name: "Flory",
        last_name: "Hurdiss",
        code: "ADAD00110011",
        password: "0000",
        email: "fhurdiss2@washington.edu",
        location: "4444 chemin staguim, Montreal, CA",
        phone: "+353-872-204-0292",
        typeofuser: "étudiant",
        university: "UQAM",
    },
    {
        id: 4,
        first_name: "Bob",
        last_name: "Greg",
        code: "EMPL00110011",
        password: "0000",
        email: "employeur@washington.edu",
        location: "4444 chemin staguim, Montreal, CA",
        phone: "+353-872-204-0292",
        typeofuser: "employeur",
        university: "Entreprise",
    },
];
